# Generated by Django 4.2.7 on 2023-11-08 23:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCostos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_horas', models.DecimalField(decimal_places=0, max_digits=20)),
                ('nivel', models.CharField(max_length=45)),
                ('proyecto_curricular', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('A', 'Pregrado'), ('B', 'Maestría'), ('C', 'Doctorado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoCurricular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('departamentos', models.ManyToManyField(blank=True, related_name='usuarios', to='AppDocent.departamento')),
                ('facultades', models.ManyToManyField(blank=True, related_name='usuarios', to='AppDocent.facultad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('horas_semanales', models.IntegerField()),
                ('centro_costos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.centrocostos')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dedicacion', models.IntegerField()),
                ('categoria_docente', models.IntegerField()),
                ('dedicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.dedicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vinculacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.vinculacion')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadInvestigativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funcion', models.CharField(max_length=45)),
                ('acta_departamento', models.CharField(max_length=15)),
                ('acta_facultad', models.CharField(max_length=15)),
                ('titulo_proyecto', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.tipoactividad')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.nivel')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadDocente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('funcion', models.CharField(max_length=45)),
                ('numero_estudiantes', models.IntegerField()),
                ('es_compartido', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.tipoactividad')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.nivel')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.profesor')),
                ('proyecto_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.proyectocurricular')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadGestion',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppDocent.profesor')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDocent.tipoactividad')),
            ],
        ),
    ]
