# Generated by Django 4.2.7 on 2023-11-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDocent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocostos',
            name='descripcion',
            field=models.CharField(choices=[('A', 'Prueba centro costos'), ('B', ''), ('C', '')], max_length=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(choices=[('A', 'Ingeniería'), ('B', ''), ('C', '')], max_length=1),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='descripcion',
            field=models.CharField(choices=[('A', 'Sistemas'), ('B', ''), ('C', '')], max_length=1),
        ),
        migrations.AlterField(
            model_name='proyectocurricular',
            name='descripcion',
            field=models.CharField(choices=[('A', 'Curricular prueba'), ('B', ''), ('C', '')], max_length=1),
        ),
    ]
